# Generated by Django 4.1 on 2022-08-27 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='descriptions',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='descriptions',
            new_name='description',
        ),
    ]
